package com.ww.mapper;

import com.ww.entity.Saldetail;
import com.ww.entity.SaldetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SaldetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    long countByExample(SaldetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int deleteByExample(SaldetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int deleteByPrimaryKey(Integer sdetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int insert(Saldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int insertSelective(Saldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    List<Saldetail> selectByExample(SaldetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    Saldetail selectByPrimaryKey(Integer sdetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Saldetail record, @Param("example") SaldetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByExample(@Param("record") Saldetail record, @Param("example") SaldetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByPrimaryKeySelective(Saldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saldetail
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByPrimaryKey(Saldetail record);
}