package com.ww.mapper;

import com.ww.entity.Saleorder;
import com.ww.entity.SaleorderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SaleorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    long countByExample(SaleorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int deleteByExample(SaleorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int deleteByPrimaryKey(Integer salorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int insert(Saleorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int insertSelective(Saleorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    List<Saleorder> selectByExample(SaleorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    Saleorder selectByPrimaryKey(Integer salorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Saleorder record, @Param("example") SaleorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByExample(@Param("record") Saleorder record, @Param("example") SaleorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByPrimaryKeySelective(Saleorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    int updateByPrimaryKey(Saleorder record);

    int max();
}