package com.ww.entity;

import java.io.Serializable;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gsId
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private Integer gsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.invtNum
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private Integer invtnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.invtMin
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private String invtmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gsId
     *
     * @return the value of goods.gsId
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public Integer getGsid() {
        return gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gsId
     *
     * @param gsid the value for goods.gsId
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setGsid(Integer gsid) {
        this.gsid = gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit
     *
     * @return the value of goods.unit
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit
     *
     * @param unit the value for goods.unit
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.invtNum
     *
     * @return the value of goods.invtNum
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public Integer getInvtnum() {
        return invtnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.invtNum
     *
     * @param invtnum the value for goods.invtNum
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setInvtnum(Integer invtnum) {
        this.invtnum = invtnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.invtMin
     *
     * @return the value of goods.invtMin
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public String getInvtmin() {
        return invtmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.invtMin
     *
     * @param invtmin the value for goods.invtMin
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setInvtmin(String invtmin) {
        this.invtmin = invtmin == null ? null : invtmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gsid=").append(gsid);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", unit=").append(unit);
        sb.append(", invtnum=").append(invtnum);
        sb.append(", invtmin=").append(invtmin);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}