package com.ww.entity;

import java.util.ArrayList;
import java.util.List;

public class SaleorderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public SaleorderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaloridIsNull() {
            addCriterion("salOrId is null");
            return (Criteria) this;
        }

        public Criteria andSaloridIsNotNull() {
            addCriterion("salOrId is not null");
            return (Criteria) this;
        }

        public Criteria andSaloridEqualTo(Integer value) {
            addCriterion("salOrId =", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridNotEqualTo(Integer value) {
            addCriterion("salOrId <>", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridGreaterThan(Integer value) {
            addCriterion("salOrId >", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridGreaterThanOrEqualTo(Integer value) {
            addCriterion("salOrId >=", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridLessThan(Integer value) {
            addCriterion("salOrId <", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridLessThanOrEqualTo(Integer value) {
            addCriterion("salOrId <=", value, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridIn(List<Integer> values) {
            addCriterion("salOrId in", values, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridNotIn(List<Integer> values) {
            addCriterion("salOrId not in", values, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridBetween(Integer value1, Integer value2) {
            addCriterion("salOrId between", value1, value2, "salorid");
            return (Criteria) this;
        }

        public Criteria andSaloridNotBetween(Integer value1, Integer value2) {
            addCriterion("salOrId not between", value1, value2, "salorid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andOrddateIsNull() {
            addCriterion("ordDate is null");
            return (Criteria) this;
        }

        public Criteria andOrddateIsNotNull() {
            addCriterion("ordDate is not null");
            return (Criteria) this;
        }

        public Criteria andOrddateEqualTo(String value) {
            addCriterion("ordDate =", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateNotEqualTo(String value) {
            addCriterion("ordDate <>", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateGreaterThan(String value) {
            addCriterion("ordDate >", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateGreaterThanOrEqualTo(String value) {
            addCriterion("ordDate >=", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateLessThan(String value) {
            addCriterion("ordDate <", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateLessThanOrEqualTo(String value) {
            addCriterion("ordDate <=", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateLike(String value) {
            addCriterion("ordDate like", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateNotLike(String value) {
            addCriterion("ordDate not like", value, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateIn(List<String> values) {
            addCriterion("ordDate in", values, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateNotIn(List<String> values) {
            addCriterion("ordDate not in", values, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateBetween(String value1, String value2) {
            addCriterion("ordDate between", value1, value2, "orddate");
            return (Criteria) this;
        }

        public Criteria andOrddateNotBetween(String value1, String value2) {
            addCriterion("ordDate not between", value1, value2, "orddate");
            return (Criteria) this;
        }

        public Criteria andTotalsumIsNull() {
            addCriterion("totalSum is null");
            return (Criteria) this;
        }

        public Criteria andTotalsumIsNotNull() {
            addCriterion("totalSum is not null");
            return (Criteria) this;
        }

        public Criteria andTotalsumEqualTo(Double value) {
            addCriterion("totalSum =", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumNotEqualTo(Double value) {
            addCriterion("totalSum <>", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumGreaterThan(Double value) {
            addCriterion("totalSum >", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumGreaterThanOrEqualTo(Double value) {
            addCriterion("totalSum >=", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumLessThan(Double value) {
            addCriterion("totalSum <", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumLessThanOrEqualTo(Double value) {
            addCriterion("totalSum <=", value, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumIn(List<Double> values) {
            addCriterion("totalSum in", values, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumNotIn(List<Double> values) {
            addCriterion("totalSum not in", values, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumBetween(Double value1, Double value2) {
            addCriterion("totalSum between", value1, value2, "totalsum");
            return (Criteria) this;
        }

        public Criteria andTotalsumNotBetween(Double value1, Double value2) {
            addCriterion("totalSum not between", value1, value2, "totalsum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table saleorder
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 26 14:04:46 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table saleorder
     *
     * @mbg.generated Tue Nov 26 14:04:46 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}